import { Dimensions } from 'react-native';
import Constants from 'expo-constants';
const SCREEN_HEIGHT = Dimensions.get('window').height;
const SCREEN_WIDTH = Dimensions.get('window').width;
const C504Default = {
  container: {
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#F8F5F6',
    width: SCREEN_WIDTH,
    flex: 1,
  },
  webviewContainer: {
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#F8F5F6',
    width: SCREEN_WIDTH,
    flex: 1,
    resizeMode: 'cover'
  },
  containerContent: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width: SCREEN_WIDTH,
  },
  formContainer: {
    width: SCREEN_WIDTH * 0.8,
    flex: 1,
    //height: SCREEN_HEIGHT,
    justifyContent: 'center',
  },
  inputStyle: {
    alignSelf: 'center',
    backgroundColor: '#F8F5F6',
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#D2416C33',
    padding: 12,
    marginBottom: 10,
    width: SCREEN_WIDTH * 0.76,
    minHeight: 44,
    letterSpacing: 0.64,
  },
  shadowProp: {
    shadowColor: 'red',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
  buttonShadowProp: {
    shadowColor: '#4E7CD54D',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
  boxLabel: {
    padding: 5,
    fontSize: 14, 
    letterSpacing: 0.64,
    color: '#190036',
  },
  important: {
    color: '#F44646',
    fontSize: 16, 
  },
  submitButton: {
    alignSelf: 'center',
    height: 50,
    width: SCREEN_WIDTH * 0.8,
    backgroundColor: '#E68D41',
    borderRadius: 27,
    marginTop: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  smallButton: {
    alignSelf: 'center',
    height: 40,
    width: SCREEN_WIDTH * 0.2,
    backgroundColor: '#E68D41',
    borderRadius: 20,
    marginTop: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chatSellerButton: {
    alignSelf: 'center',
    height: 50,
    width: SCREEN_WIDTH * 0.125,
    borderWidth: 1,
    borderColor: '#D0436D80',
    backgroundColor: '#ffffff',
    borderRadius: 7,
    margin: 5,
    marginLeft: 0,
    marginVertical: 15,
    padding: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  contactButton: {
    alignSelf: 'center',
    height: 50,
    width: SCREEN_WIDTH * 0.125,
    backgroundColor: '#E68D41',
    borderRadius: 7,
    margin: 5,
    marginVertical: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  fbButton: {
    alignSelf: 'center',
    height: 54,
    width: SCREEN_WIDTH * 0.76,
    backgroundColor: '#1877F2',
    borderRadius: 27,
    alignItems: 'center',
    marginTop: 10,
    justifyContent: 'center',
  },
  buttonText: {
    color: '#FFFFFF', 
    fontSize: 14,
    letterSpacing: 0.64,
    textAlign: 'center',
  },
  chatButtonText: {
    color: '#D0436D', 
    fontSize: 16,
    letterSpacing: 0.32,
    textAlign: 'center',
  },
  contactButtonText: {
    color: '#ffffff', 
    fontSize: 16,
    paddingHorizontal: 8,
    letterSpacing: 0.32,
    textAlign: 'center',
  },
  topMenuStrip: {
    position: 'absolute',
    flexDirection: 'row',
    width: SCREEN_WIDTH,
    justifyContent: 'space-between',
    top: 20,
    alignItems: 'center',
    paddingHorizontal: 25,
  },
  //JOB PORTAL
  JobCard: {
    role: {
      color: '#4D4D4D',
      fontSize: 14, 
      fontWeight: 'bold',
      lineHeight: 20,
      letterSpacing: 0.42,
    },
    role2: {
      color: '#ffffff', 
      fontWeight: 'bold',
      letterSpacing: 0.42,
      textShadowColor: '#000000',
      textShadowOffset: { width: 1, height: 3 },
      textShadowRadius: 5,
    },
    company: {
      color: '#D2416C',
      fontSize: 16,
      letterSpacing: 0.42,
    },
  },
  //EBI MALL
  ProductCard: {
    title: {
      color: '#4D4D4D',
      fontSize: 14, 
      fontWeight: 'bold',
      lineHeight: 20,
      letterSpacing: 0.42,
    },
    bigtitle: {
      color: '#4D4D4D',
      fontSize: 20, 
      fontWeight: 'bold',
      lineHeight: 25,
      letterSpacing: 0.42,
      paddingVertical: 10,
    },
    bigtitleapplications: {
      color: '#4D4D4D',
      fontSize: 16, 
      fontWeight: 'bold',
      lineHeight: 25,
      letterSpacing: 0.42,
      paddingVertical: 10,
      marginLeft: 20,
    },
    price: {
      color: '#D2416C',
      fontSize: 16,
      letterSpacing: 0.42,
      marginTop: 10,
    },
    bigprice: {
      color: '#D2416C',
      fontSize: 24, 
      letterSpacing: 0.42,
      paddingVertical: 25,
    },
  },
  Article: {
    articleContainer: {
      width: SCREEN_WIDTH * 0.9,
      maxWidth: SCREEN_WIDTH * 0.9,
      marginVertical: 5,
      paddingBottom: 20,
      backgroundColor: '#FFF',
      borderRadius: 20,
      //borderWidth: 1,
      borderColor: '#D2416C26',
      flexDirection: 'column',
      alignSelf: 'center',
    },
    articleDetailContainer: {
      width: SCREEN_WIDTH * 0.9,
      maxWidth: SCREEN_WIDTH * 0.9,
      marginVertical: 5,
      paddingBottom: 20,
      borderRadius: 20,
      //borderWidth: 1,
      borderColor: '#D2416C26',
      flexDirection: 'column',
      alignSelf: 'center',
    },
    title: {
      color: '#4D4D4D',
      fontSize: 18, 
      fontWeight: 'bold',
      lineHeight: 20,
      letterSpacing: 0.42,
    },
    description: {
      color: '#4D4D4D',
      fontSize: 14,
      letterSpacing: 0.42,
      paddingTop: 10,
      textAlign: 'justify',
    },
    footerText: {
      fontSize: 12,
      fontWeight: 'bold',
      color: '#868686',
    },
  },
  //TIMELINE CONTENT
  PostCard: {
    postContainer: {
      width: SCREEN_WIDTH * 0.9,
      maxWidth: SCREEN_WIDTH * 0.9,
      marginVertical: 5,
      paddingBottom: 20,
      //backgroundColor: "#FFF",
      borderRadius: 20,
      //borderWidth: 1,
      borderColor: '#D2416C26',
      flexDirection: 'column',
      alignSelf: 'center',
    },
    postHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingVertical: 10,
      alignItems: 'center',
    },
    authorSection: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    authorImage: {
      width: 40,
      height: 40,
      borderRadius: 10,
    },
    jobAuthorImage: {
      width: 60,
      height: 60,
      borderRadius: 10,
    },
    followAuthorImage: {
      width: 80,
      height: 80,
      borderRadius: 10,
    },
    commentImage: {
      width: 30,
      height: 30,
      borderRadius: 5,
    },
    commentInputStyle: {
      alignSelf: 'center',
      backgroundColor: '#F8F5F6',
      borderRadius: 5,
      borderWidth: 1,
      borderColor: '#C1C1C1',
      padding: 12,
      paddingVertical: 8,
      paddingRight: 40,
      width: SCREEN_WIDTH * 0.76,
      height: 44,
      letterSpacing: 0.64,
    },
    authorName: { fontSize: 14, fontWeight: 'bold', color: '#4D4D4D' },
    authorFollowerCount: { fontSize: 10 },
    postImage: {
      width: '100%',
      height: 200,
      borderRadius: 10,
    },
    title: {
      color: '#4D4D4D',
      fontSize: 15, 
      fontWeight: 'bold',
      lineHeight: 20,
      letterSpacing: 0.42,
    },
    description: {
      color: '#4D4D4D',
      fontSize: 14,
      //letterSpacing: 0.42,
      paddingTop: 10,
      textAlign: 'justify',
    },
  },
};

export default C504Default;
